version: '3.9'

services:
  # ===== Backend services =====
  user-service:
    build: ./backend/user-service
    container_name: chatbox-app-user-service
    env_file:
      - ./backend/user-service/.env
    depends_on:
      - db
      - kafka
    command: ["sh", "./wait-for-db.sh", "node", "server.js"]
    ports:
      - "3001:3001"
    working_dir: /usr/src/app
    volumes:
      - ./backend/user-service:/usr/src/app

  chat-service:
    build: ./backend/chat-service
    container_name: chatbox-app-chat-service
    env_file:
      - ./backend/chat-service/.env
    depends_on:
      - cassandra
      - user-service
      - kafka
    ports:
      - "3000:3000"
    working_dir: /usr/src/app
    volumes:
      - ./backend/chat-service:/usr/src/app
    command: ["sh", "wait-for-cassandra.sh", "node", "server.js"]

  # media-service:
  #   build: ./backend/media-service
  #   container_name: chatbox-app-media-service
  #   env_file:
  #     - ./backend/media-service/.env
  #   depends_on:
  #     - minio
  #     - kafka
  #   ports:
  #     - "3002:3002"
  #   working_dir: /usr/src/app
  #   volumes:
  #     - ./backend/media-service:/usr/src/app
  #     - ./backend/media-service/uploads:/usr/src/app/uploads
  #   command: ["node", "server.js"]

  # ===== Databases =====
  db:
    image: postgres:16-alpine
    container_name: user-db
    env_file:
      - ./backend/user-service/.env
    volumes:
      - user-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cassandra:
    image: cassandra:4.1
    container_name: cassandra-db
    ports:
      - "9042:9042"
    volumes:
      - cassandra-data:/var/lib/cassandra

  # minio:
  #   image: minio/minio:latest
  #   container_name: minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   environment:
  #     MINIO_ROOT_USER: admin
  #     MINIO_ROOT_PASSWORD: admin123
  #   command: server /data --console-address ":9001"
  #   volumes:
  #     - minio-data:/data

  # ===== Kafka + Zookeeper =====
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

volumes:
  user-db-data:
  cassandra-data:
  minio-data:
